
openapi: 3.0.0
info:
  title: Listing Service API
  version: "1.0"
  description: API for managing listings, reviews and photos
paths:
  /api/listings:
    get:
      summary: Get approved listings with filters
      tags: [Listings]
      parameters:
        - in: query
          name: city
          schema: {type: string}
        - in: query
          name: category
          schema: {type: string}
        - in: query
          name: min_price
          schema: {type: number}
        - in: query
          name: max_price
          schema: {type: number}
        - in: query
          name: limit
          schema: {type: integer}
        - in: query
          name: offset
          schema: {type: integer}
      responses:
        "200":
          description: List of approved listings
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Listing'
    post:
      summary: Create new listing
      tags: [Listings]
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Listing'
      responses:
        "201":
          description: Listing created

  /api/listings/{id}:
    get:
      summary: Get listing by ID
      tags: [Listings]
      parameters:
        - in: path
          name: id
          required: true
          schema: {type: string}
      responses:
        "200":
          description: Listing detail
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Listing'
    put:
      summary: Update listing
      tags: [Listings]
      parameters:
        - in: path
          name: id
          required: true
          schema: {type: string}
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Listing'
      responses:
        "200":
          description: Listing updated
    delete:
      summary: Delete listing
      tags: [Listings]
      parameters:
        - in: path
          name: id
          required: true
          schema: {type: string}
      responses:
        "200":
          description: Listing deleted

  /api/listings/{id}/reviews:
    get:
      summary: Get listing reviews
      tags: [Reviews]
      parameters:
        - in: path
          name: id
          required: true
          schema: {type: string}
      responses:
        "200":
          description: List of reviews
    post:
      summary: Create review
      tags: [Reviews]
      parameters:
        - in: path
          name: id
          required: true
          schema: {type: string}
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ReviewRequest'
      responses:
        "201":
          description: Review created

  /api/listings/{id}/photo:
    post:
      summary: Upload listing photo
      tags: [Photos]
      parameters:
        - in: path
          name: id
          required: true
          schema: {type: string}
      requestBody:
        required: true
        content:
          multipart/form-data:
            schema:
              type: object
              properties:
                file:
                  type: string
                  format: binary
      responses:
        "200":
          description: Photo uploaded
    get:
      summary: Download listing photo
      tags: [Photos]
      parameters:
        - in: path
          name: id
          required: true
          schema: {type: string}
      responses:
        "200":
          description: Listing photo

  /api/listings/admin/pending:
    get:
      summary: Get pending listings (admin)
      tags: [Admin]
      parameters:
        - in: query
          name: limit
          schema: {type: integer}
        - in: query
          name: offset
          schema: {type: integer}
      responses:
        "200":
          description: List of pending listings

  /api/listings/admin/{id}/approve:
    put:
      summary: Approve listing (admin)
      tags: [Admin]
      parameters:
        - in: path
          name: id
          required: true
          schema: {type: string}
      responses:
        "200":
          description: Listing approved

  /api/listings/admin/{id}/reject:
    put:
      summary: Reject listing (admin)
      tags: [Admin]
      parameters:
        - in: path
          name: id
          required: true
          schema: {type: string}
      responses:
        "200":
          description: Listing rejected

components:
  schemas:
    Listing:
      type: object
      properties:
        id:
          type: string
        ownerId:
          type: string
        deviceId:
          type: string
        title:
          type: string
        description:
          type: string
        price:
          type: number
        category:
          type: string
        city:
          type: string
        region:
          type: string
        imageUrl:
          type: string
        status:
          type: string
        type:
          type: string
        averageRating:
          type: number
        createdAt:
          type: string
        updatedAt:
          type: string
    ReviewRequest:
      type: object
      properties:
        userId:
          type: string
        rating:
          type: integer
        comment:
          type: string
