
openapi: 3.0.0
info:
  title: Listing Service API
  version: "1.0"
  description: |
    Сервис для управления объявлениями (CRUD + модерация).  
    Базовый путь: `/api/v1`.  
    Для админских маршрутов требуется JWT (Bearer) с ролью ADMIN.
servers:
  - url: http://localhost:8080
    description: Local server
components:
  securitySchemes:
    BearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
  schemas:
    Listing:
      type: object
      required:
        - id
        - owner_id
        - title
        - description
        - price
        - category
        - city
        - region
        - image_url
        - status
        - type
        - created_at
        - updated_at
      properties:
        id:
          type: string
        owner_id:
          type: string
        title:
          type: string
        description:
          type: string
        price:
          type: number
          format: double
        category:
          type: string
        city:
          type: string
        region:
          type: string
        image_url:
          type: string
        status:
          type: string
          enum: [pending, approved, rejected]
        type:
          type: string
          enum: [rent, sale, search]
        created_at:
          type: string
          format: date-time
        updated_at:
          type: string
          format: date-time
    ListingCreateRequest:
      type: object
      required:
        - owner_id
        - title
        - description
        - price
        - category
        - city
        - region
        - image_url
      properties:
        owner_id:
          type: string
        title:
          type: string
        description:
          type: string
        price:
          type: number
          format: double
        category:
          type: string
        city:
          type: string
        region:
          type: string
        image_url:
          type: string
        type:
          type: string
          enum: [rent, sale, search]
    ListingUpdateRequest:
      type: object
      required:
        - title
        - description
        - price
        - category
        - city
        - region
        - image_url
        - status
        - type
      properties:
        title:
          type: string
        description:
          type: string
        price:
          type: number
          format: double
        category:
          type: string
        city:
          type: string
        region:
          type: string
        image_url:
          type: string
        status:
          type: string
          enum: [pending, approved, rejected]
        type:
          type: string
          enum: [rent, sale, search]
    ErrorResponse:
      type: object
      properties:
        error:
          type: string
    SuccessResponse:
      type: object
      properties:
        message:
          type: string

paths: {}
